# Generated by Django 5.2.5 on 2025-12-29 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='device_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='tracking_interval',
            field=models.IntegerField(default=30),
        ),
        migrations.CreateModel(
            name='TrackingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android App'), ('ios', 'iOS App')], max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('locations_count', models.IntegerField(default=0)),
                ('distance_traveled', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='api.driver')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='tracking_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='api.trackingsession'),
        ),
    ]
